export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      ggggggggggga;sdklfja;sldfjasf
      <body>{children}</body>
    </html>
  );
}
